### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by itsdfish** [itsdfish/ACTRModels.jl#2]
@JuliaRegistrator register()

**Comment by itsdfish** [comment]
Hi @goedman. Sorry to bother you. I am having trouble registering this new package. Since you have done this before, I was wondering if you might be able to explain step two in the [instructions](https://juliaregistries.github.io/Registrator.jl/stable/webui/#Usage-(For-Package-Maintainers)-1)? It's not clear to me what it is referring to.

**Comment by goedman** [comment]
Hi Chris,
.
I’m a bit confused if this is needed. In fact I just registered our/my Github Organizations, but I never did that in the past.
The WebUI only sees Github Organizations it seems to me. See below screenshot. Or am I looking in the wrong place?

Did you try the same route as you’re following when updating MCMCBenchmarks.jl? I.e.:

1. Create an issue with say as subject “New package ACTRModels.jl”
2. And with contents: @JuliaRegistrator `register()`

If that doesn’t work I’ll try it with StructuralCausalModels.jl (which is brand new as well).

Rob J Goedman
goedman@icloud.com

**Comment by itsdfish** [comment]
Thanks Rob. I tried calling the JuliaRegister above and in a new issue with a different title, but to no avail. Maybe I need to ask on Discourse.

**Comment by itsdfish** [comment]
Thanks Rob. I tried "@JuliaRegistrator register()

**Comment by itsdfish** [comment]
@goedman, I didn't have registrator configured as an app.
